---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: java-web-app-deployment
spec:
 replicas: 2
 strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1     # Max 1 Pod can be unavailable during the update
      maxSurge: 1           # Allow 1 extra Pod above desired number of replicas
 selector: 
   matchLabels: 
     app: java-web-app
 template:
  metadata:
   name: java-web-app-pod
   labels:
     app: java-web-app	 
  spec: 
    containers:
    - name: java-web-app-container
      image: devopsdktraining/java-deepak-webapp:2
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: java-web-app-svc
spec:
  type: NodePort
  selector:
   app: java-web-app
  ports:
   - port: 80
     targetPort: 8080
...
